[styling=FreeBasic]

[keywords]
# Comandi principali e funzioni di Persil (BBC BASIC in francese)
keywords=a abs acs adval al aleatoire aller allersous alors appeler asc asn atn bget# bput# car$ chaine$ chainer cos count def deg delete dessiner dim div donnees droite$ effacer effacertout endproc entier erl erreur et eval executer exp ext# false fermer fin finfichier fn gauche$ gcol get$ himem imprimer inkey input# instr jusqua largeur lecture lire ln load local log lomem long milieu$ mod move new non old openin openout openup oscli ou pas plot point pos pour prendre print# proc ptr# quit racine rem repeat report restauration retour save si signe sin soit son stop string$ suivant tan tantque time touche$ true usr val vdu

[settings]
lexer_filetype=FreeBasic
# Estensioni predefinite
extension=bas
# Simbolo per i commenti
comment_single=REM

[build-menu]
# Imposta automaticamente i comandi di esecuzione per questo linguaggio!
EX_00_LB=_Executer
EX_00_CM=./tb "%f" persil.txt -c
EX_00_WD=
