[styling=FreeBasic]

[keywords]
# Comandi principali e funzioni di Azafran (BBC BASIC in spagnolo)
keywords=a abs acs adval al aleatorio anchura asc asn atn bget# borrar bput# cadena$ car$ cerrar cos count datos def deg delete derecha$ dibujar dim div ejecutar encadenar endproc entero entonces erl error eval exp ext# false fin finfichero fn gcol get$ hasta himem imprimir inkey input# instr ir irsub izquierda$ lectura leer limpiar llamar ln load local log lomem long medio$ mientras mod move new no o obtener old openin openout openup oscli para parar paso plot pos print# proc ptr# punto quit raiz rem repeat report restaurar save sea sen si signo siguiente sonido string$ tan tecla$ time true usr val vdu volver y

[settings]
lexer_filetype=FreeBasic
# Simbolo per i commenti
comment_single=REM
# Estensioni predefinite
extension=bas

[build-menu]
# Imposta automaticamente i comandi di esecuzione per questo linguaggio!
EX_00_LB=_Ejecutar
EX_00_CM=./tb "%f" azafran.txt
EX_00_WD=

