[styling=FreeBasic]

[keywords]
# Comandi principali e funzioni del BASILICO
keywords=a acs adval al allora asc asn ass atn avvia bget# bput# car$ cas chiama chiudi cos count dati def deg delete destra$ dim disegna div e endproc erl errore esp eval ext# false fdf fine fino fn gcol get$ himem inkey input# instr int leggi lettura ln load local log lomem lun mentre mez$ misure mod move new non nota o old openin openout openup oscli passa passo per plot pos prendi print# proc psc ptr# pulisci punto quit repeat report rileggi rqu save se seguente sen sgn sia sinistra$ stampa stop str$ string$ suono tan tasto$ time torna true usr vai vaisub val vdu

[settings]
lexer_filetype=FreeBasic
# Simbolo per i commenti
comment_single=NOTA
# Estensioni predefinite
extension=bas

[build-menu]
# Imposta automaticamente i comandi di esecuzione per questo linguaggio!
EX_00_LB=_Esegui
EX_00_CM=./tb "%f"
EX_00_WD=
